# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HashRetrieval_server.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 892)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 760, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(120, 20, 301, 531))
        self.groupBox.setObjectName("groupBox")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 141, 16))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 111, 16))
        self.label_6.setObjectName("label_6")
        self.label_ = QtWidgets.QLabel(self.groupBox)
        self.label_.setGeometry(QtCore.QRect(10, 150, 101, 16))
        self.label_.setObjectName("label_")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 190, 81, 16))
        self.label_8.setObjectName("label_8")
        self.progressBar_extrator = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_extrator.setGeometry(QtCore.QRect(90, 230, 211, 23))
        self.progressBar_extrator.setProperty("value", 0)
        self.progressBar_extrator.setObjectName("progressBar_extrator")
        self.label_extrator = QtWidgets.QLabel(self.groupBox)
        self.label_extrator.setGeometry(QtCore.QRect(10, 230, 81, 16))
        self.label_extrator.setObjectName("label_extrator")
        self.label_match = QtWidgets.QLabel(self.groupBox)
        self.label_match.setGeometry(QtCore.QRect(10, 270, 81, 16))
        self.label_match.setObjectName("label_match")
        self.progressBar_match = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_match.setGeometry(QtCore.QRect(90, 270, 211, 23))
        self.progressBar_match.setProperty("value", 0)
        self.progressBar_match.setObjectName("progressBar_match")
        self.label_alltime = QtWidgets.QLabel(self.groupBox)
        self.label_alltime.setGeometry(QtCore.QRect(160, 30, 91, 16))
        self.label_alltime.setText("")
        self.label_alltime.setObjectName("label_alltime")
        self.label_average = QtWidgets.QLabel(self.groupBox)
        self.label_average.setGeometry(QtCore.QRect(130, 70, 101, 16))
        self.label_average.setText("")
        self.label_average.setObjectName("label_average")
        self.label_Rank1 = QtWidgets.QLabel(self.groupBox)
        self.label_Rank1.setGeometry(QtCore.QRect(100, 150, 111, 16))
        self.label_Rank1.setText("")
        self.label_Rank1.setObjectName("label_Rank1")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView.setGeometry(QtCore.QRect(10, 360, 281, 151))
        self.graphicsView.setObjectName("graphicsView")
        self.label_match_2 = QtWidgets.QLabel(self.groupBox)
        self.label_match_2.setGeometry(QtCore.QRect(10, 320, 81, 16))
        self.label_match_2.setObjectName("label_match_2")
        self.label_1 = QtWidgets.QLabel(self.groupBox)
        self.label_1.setGeometry(QtCore.QRect(10, 110, 101, 16))
        self.label_1.setObjectName("label_1")
        self.label_Rank1_2 = QtWidgets.QLabel(self.groupBox)
        self.label_Rank1_2.setGeometry(QtCore.QRect(100, 110, 111, 16))
        self.label_Rank1_2.setText("")
        self.label_Rank1_2.setObjectName("label_Rank1_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(260, 570, 431, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox_dataset = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_dataset.setGeometry(QtCore.QRect(190, 80, 121, 22))
        self.comboBox_dataset.setObjectName("comboBox_dataset")
        self.comboBox_dataset.addItem("")
        self.comboBox_dataset.addItem("")
        self.comboBox_dataset.addItem("")
        self.lineEdit_imagenum = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_imagenum.setGeometry(QtCore.QRect(190, 120, 191, 21))
        self.lineEdit_imagenum.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_imagenum.setText("")
        self.lineEdit_imagenum.setObjectName("lineEdit_imagenum")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(20, 80, 121, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 141, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 121, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton_choosemodel = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_choosemodel.setGeometry(QtCore.QRect(110, 30, 93, 28))
        self.pushButton_choosemodel.setObjectName("pushButton_choosemodel")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(220, 40, 81, 16))
        self.label_7.setObjectName("label_7")
        self.pushButton_choosemodel_deep = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_choosemodel_deep.setGeometry(QtCore.QRect(310, 30, 93, 28))
        self.pushButton_choosemodel_deep.setObjectName("pushButton_choosemodel_deep")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(500, 20, 311, 531))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(10, 30, 141, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(10, 70, 111, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setGeometry(QtCore.QRect(10, 150, 101, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setGeometry(QtCore.QRect(10, 190, 81, 16))
        self.label_22.setObjectName("label_22")
        self.progressBar_realextrator = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar_realextrator.setGeometry(QtCore.QRect(90, 230, 211, 23))
        self.progressBar_realextrator.setProperty("value", 0)
        self.progressBar_realextrator.setObjectName("progressBar_realextrator")
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(10, 230, 81, 16))
        self.label_23.setObjectName("label_23")
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setGeometry(QtCore.QRect(10, 270, 81, 16))
        self.label_25.setObjectName("label_25")
        self.progressBar_realmatch = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar_realmatch.setGeometry(QtCore.QRect(90, 270, 211, 23))
        self.progressBar_realmatch.setProperty("value", 0)
        self.progressBar_realmatch.setObjectName("progressBar_realmatch")
        self.label_alltime_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_alltime_2.setGeometry(QtCore.QRect(170, 30, 91, 16))
        self.label_alltime_2.setText("")
        self.label_alltime_2.setObjectName("label_alltime_2")
        self.label_averagetime = QtWidgets.QLabel(self.groupBox_2)
        self.label_averagetime.setGeometry(QtCore.QRect(130, 70, 101, 16))
        self.label_averagetime.setText("")
        self.label_averagetime.setObjectName("label_averagetime")
        self.label_realRank1 = QtWidgets.QLabel(self.groupBox_2)
        self.label_realRank1.setGeometry(QtCore.QRect(100, 150, 111, 16))
        self.label_realRank1.setText("")
        self.label_realRank1.setObjectName("label_realRank1")
        self.label_match_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_match_3.setGeometry(QtCore.QRect(10, 319, 81, 16))
        self.label_match_3.setObjectName("label_match_3")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView_2.setGeometry(QtCore.QRect(10, 360, 291, 151))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label_33 = QtWidgets.QLabel(self.groupBox_2)
        self.label_33.setGeometry(QtCore.QRect(10, 110, 101, 16))
        self.label_33.setObjectName("label_33")
        self.label_realRank1_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_realRank1_3.setGeometry(QtCore.QRect(100, 110, 111, 16))
        self.label_realRank1_3.setText("")
        self.label_realRank1_3.setObjectName("label_realRank1_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 760, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 880, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_choosemodel.clicked.connect(MainWindow.slot_hash)
        self.pushButton_choosemodel_deep.clicked.connect(MainWindow.slot_deep)
        self.pushButton.clicked.connect(MainWindow.slot_search_hash)
        self.pushButton_2.clicked.connect(MainWindow.slot_search_deep)
        #self.pushButton_2.clicked.connect(MainWindow.slot_allbegin)
        
        #self.pushButton_2.clicked.connect(MainWindow.slot_search_hash)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_choosemodel, self.comboBox_dataset)
        MainWindow.setTabOrder(self.comboBox_dataset, self.lineEdit_imagenum)
        MainWindow.setTabOrder(self.lineEdit_imagenum, self.pushButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "行人再识别检索系统"))
        self.pushButton.setText(_translate("MainWindow", "哈希检索"))
        self.groupBox.setTitle(_translate("MainWindow", "哈希结合方法"))
        self.label_4.setText(_translate("MainWindow", "平均特征提取时间："))
        self.label_6.setText(_translate("MainWindow", "平均匹配时间："))
        self.label_.setText(_translate("MainWindow", "Rank-1精度："))
        self.label_8.setText(_translate("MainWindow", "检索结果："))
        self.label_extrator.setText(_translate("MainWindow", "特征提取："))
        self.label_match.setText(_translate("MainWindow", "检索匹配："))
        self.label_match_2.setText(_translate("MainWindow", "可视化结果："))
        self.label_1.setText(_translate("MainWindow", "mAP:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "检索选择"))
        self.comboBox_dataset.setItemText(0, _translate("MainWindow", "Market-1501"))
        self.comboBox_dataset.setItemText(1, _translate("MainWindow", "DukeMTMC-reID"))
        self.comboBox_dataset.setItemText(2, _translate("MainWindow", "CUHK03"))
        self.lineEdit_imagenum.setPlaceholderText(_translate("MainWindow", "请输入基准图像数..."))
        self.label.setText(_translate("MainWindow", "选择数据集："))
        self.label_2.setText(_translate("MainWindow", "输入检索图像数量："))
        self.label_3.setText(_translate("MainWindow", "哈希模型："))
        self.pushButton_choosemodel.setText(_translate("MainWindow", "打开"))
        self.label_7.setText(_translate("MainWindow", "深度模型："))
        self.pushButton_choosemodel_deep.setText(_translate("MainWindow", "打开"))
        self.groupBox_2.setTitle(_translate("MainWindow", "实值特征方法"))
        self.label_19.setText(_translate("MainWindow", "平均特征提取时间："))
        self.label_20.setText(_translate("MainWindow", "平均匹配时间："))
        self.label_21.setText(_translate("MainWindow", "Rank-1精度："))
        self.label_22.setText(_translate("MainWindow", "检索结果："))
        self.label_23.setText(_translate("MainWindow", "特征提取："))
        self.label_25.setText(_translate("MainWindow", "检索匹配："))
        self.label_match_3.setText(_translate("MainWindow", "可视化结果："))
        self.label_33.setText(_translate("MainWindow", "mAP:"))
        self.pushButton_2.setText(_translate("MainWindow", "深度检索"))
